version: "3"

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_NODE_PORT_NUMBER=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=1234
    ports:
      - "15672:15672"
      - "5672:5672"
    # volumes:
    #   - 'rabbitmqstats_data:/bitnami'
